### ISSUE TITLE
Problem with wealth supplementary files using build.panel 

### ISSUE THREAD

**Issue by chikimecon** [floswald/psidR#23] opened 2018-06-29 10:12 UTC
Hello,

I have a question regarding the usage of the function **build.panel**. 
I am interested in constructing a panel dataset with variables from the family, individual, AND wealth supplementary files. The time period I am interested in is 1999-2015. For this time period the PSID has biannual data. 

Following the instructions of the function build.panel, I need three data.frame of variables from the 1. family, 2. individual, and 3. wealth file (I define them as famvars, indvars, and wealthvars). I also include unbalanced variables, meaning there are some variables, which are available only for certain periods. Here is a shorter version of my variables of interest:

###############################################################################
#### Generate list of variable names ###################################################

# Start with family file
famvars.fullsample = data.frame(
  year 					=c(1999, 2001, 2003, 2005, 2007, 2009, 2011, 2013, 2015),
  release.num				=c(	"ER13001", "ER17001", "ER21001", "ER25001", "ER36001", "ER42001", "ER47301", "ER53001", "ER60001"),
  splitoff.ind			=c(	"ER13005E", "ER17006", "ER21005", "ER25005", "ER36005", "ER42005", "ER47305", "ER53005", "ER60005"),
  race.head4				=c(	"ER15931", "ER19992", "ER23429", "ER27396", "ER40568", "ER46546", "ER51907", "ER57662", "ER64813"),
  ethnic.group			=c(	"ER15932", "ER19993", "ER23430", "ER27397", "ER40569", "ER46547", "ER51908", "ER57663", "ER64815")) 
  
  # Second: unbalanced variables. 2013 and 2015 are missing
  famvars.sub1 = data.frame(
    year 					=c(1999, 2001, 2003, 2005, 2007, 2009, 2011),
    W83						=c(	"ER15075", "ER19271", "ER22666", "ER26647", "ER37665", "ER43656", "ER49001"))
  
  # Third: unbalanced variables. Only available for 2013 and 2015
  famvars.sub2 = data.frame(
    year 					=c(2013, 2015),
    W83A.201315				=c("ER54763", "ER61874"),
    W91.201315				=c("ER54764", "ER61875"),
    W92.201315				=c("ER54765", "ER61876"),
    W93.201315				=c("ER54766", "ER61877"),
    W94.201315				=c("ER54767", "ER61878"),
    W95.201315				=c("ER54768", "ER61879"))
  
  # Merge family file variables all together
  famvars=merge(famvars.fullsample, famvars.sub1, all = TRUE)
  famvars=merge(famvars, famvars.sub2, all=TRUE)
  
  # Generate individual variables 
  indvars = data.frame(
    year=c(1999, 2001, 2003, 2005, 2007, 2009, 2011, 2013, 2015),
    ind.1968.int.num=c("ER33501", "ER33601", "ER33701", "ER33801", "ER33901", "ER34001", "ER34101", "ER34201", "ER34301"),
    ind.seq.num=c("ER33502", "ER33602", "ER33702", "ER33802", "ER33902", "ER34002", "ER34102", "ER34202", "ER34302"),
    ind.relation.head=c("ER33503", "ER33603", "ER33703", "ER33803", "ER33903", "ER34003", "ER34103", "ER34203", "ER34303"))
  
  # Generate wealth variables 
  wealthvars= data.frame(
    year	=c(1999, 2001, 2003, 2005, 2007),
    wlth.S400 =c("S400",  "S500",  "S600",  "S700",  "S800"),
    wlth.S401 = c("S401", "S501",  "S601",  "S701",  "S801"),
    wlth.S402	=c("S402",  "S502",  "S602",  "S702",  "S802"),
    wlth.S402A	=c("S402A", "S502A", "S602A", "S702A", "S802A"), 
    wlth.S403	=c("S403",  "S503",  "S603",  "S703",  "S803"),   
    wlth.S403A	=c("S403A", "S503A", "S603A", "S703A", "S803A"), 
    wlth.S404	=c("S404",  "S504",  "S604",  "S704",  "S804"), 
    wlth.S404A	=c("S404A", "S504A", "S604A", "S704A", "S804A"), 
    wlth.S405	=c("S405",  "S505",  "S605",  "S705",  "S805"), 
    wlth.S405A	=c("S405A", "S505A", "S605A", "S705A", "S805A"), 
    wlth.S408	=c("S408",  "S508",  "S608",  "S708",  "S808"), 
    wlth.S408A	=c("S408A", "S508A", "S608A", "S708A", "S808A"))
############################################################################

Afterwards, I downloaded all PSID data into Rda format and write down the following arguments for the function build.panel (my.dir is specified):

d.wealth= build.panel(datadir=my.dir,  
                      fam.vars=famvars, 
                      ind.vars=indvars, 
                      wealth.vars=wealthvars, 
                      design="ALL", 
                      heads.only=TRUE, verbose=TRUE) 

Then I obtain the following error, which indicates that the wealth variables cannot be found:  

----------------------------------------------------------------------------------------------------------
Error in `[.data.table`(fam.vars[list(years[iy])], , curnames, with = FALSE) : 
  column(s) not found: wlth.S400, wlth.S401, wlth.S402, wlth.S402A, wlth.S403, wlth.S403A, wlth.S404, wlth.S404A, wlth.S405, wlth.S405A, wlth.S408, wlth.S408A
In addition: Warning message:
In `[.data.table`(tmp, , `:=`((nanames), NA_real_), with = FALSE) :
  with=FALSE ignored, it isn't needed when using :=. See ?':=' for examples.
----------------------------------------------------------------------------------------------------------

I think this is happening because the function seems to search for these variables in the family data, but I could not figure out how to deal with this problem. I searched for solutions in the web and tried a bunch of stuff, but unfortunately I was not successful. If I do not include the wealth.vars, then everything seems to work. 

I would be very very greatful, if you could help me solve this problem.

Thank you in advance!

**Comment by floswald** [comment] 2018-08-15 12:38
closed as dupe of #21

**Closed by floswald** 2018-08-15 12:38 UTC
