### ISSUE TITLE
Same crash as youngceltic previously posted

### ISSUE THREAD

**Issue by mariannevb** [floswald/psidR#31] opened 2019-09-17 21:43 UTC
I'm getting the same error as https://github.com/floswald/psidR/issues/30

I ran the following using version 3.5.2 in Win10 install of Rstudio:

```
library(psidR)
library(data.table)
library(readr)
#Change the location of where you download the data
  
dd<-'c:...psid/data'
cwf = openxlsx::read.xlsx(system.file(package="psidR","psid-lists","psid.xlsx"))
food_at_home<-getNamesPSID("V4354",cwf,years=c(1974,1975))
food_away<-getNamesPSID("V4368",cwf,years=c(1974,1975))
ed_head<-getNamesPSID("V3663",cwf,years=c(1974,1975))
age_head <- getNamesPSID("ER17013", cwf, years=c(1974,1975))
educ = getNamesPSID("ER30323",cwf,years=2003)
famvars = data.frame(year=c(1974,1975),age_head=age_head,food_at_home=food_at_home)
indvars = data.frame(year=c(1974,1975),educ=educ)
# call function
build.panel(fam.vars=famvars,ind.vars=indvars,datadir=dd)
```

Everything is executing fine until the build.panel function call, which returns:

```
Error in load(file = ind.file, envir = tmp.env) : 
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning message:
file ‘ind2017er.zip’ has magic number 'PK'
  Use of save versions prior to 2 is deprecated 
```

**Comment by floswald** [comment] 2019-09-18 05:21
Thanks. I have seen that error in other contexts recently. It had to do with mixing `save` and `readRDS` improperly. Can you run this again and then post `backtrace()` here please?

**Comment by floswald** [comment] 2019-09-18 08:20
closing as duplicate of #30

**Closed by floswald** 2019-09-18 08:20 UTC
